### ISSUE TITLE
필터링 기능 추가로 인한 Request 증가 -> `Batch inference` 구현 필요

### ISSUE THREAD

**Issue by SNMHZ** [boostcampaitech3/final-project-level3-recsys-13#55]
#48 
필터링 기능 추가로 인한 Request 증가
더 빠르게 처리할 필요 발생 -> `Batch inference` 구현 으로 해결 가능
Airflow에 학습 최신화 이후 `Batch inference` 진행하도록 합시다 !!

**Comment by SNMHZ** [comment]
#57 #60 Cloud Storage를 통한 구현

**Comment by whattSUPkim** [comment]
- #96
